using Controle_de_Medicamentos.ConsoleApp.MedicalPrescriptionsModule;
using Controle_de_Medicamentos.ConsoleApp.Shared.BaseModule;

namespace Controle_de_Medicamentos.ConsoleApp.MedicalPrescriptionModule;

public interface IMedicalPrescriptionRepository : IRepository<MedicalPrescription>;
